apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  labels:
    app: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      labels:
        app: udm
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.2.8\"]"
    spec:
      containers:
        - name: udm
          image: harku/free5gc:v3.1.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "./bin/udm -c ./config/udmcfg.yaml"]
          stdin: true
          tty: true
          volumeMounts:
            - name: udm-config
              mountPath: /root/free5gc/config/udmcfg.yaml
              subPath: udmcfg.yaml
      volumes:
        - name: udm-config
          configMap:
            name: udm
