apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf
  labels:
    app: pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcf
  template:
    metadata:
      labels:
        app: pcf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.2.6\"]"
    spec:
      containers:
        - name: pcf
          image: harku/free5gc:v3.1.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "./bin/pcf -c ./config/pcfcfg.yaml"]
          stdin: true
          tty: true
          volumeMounts:
            - name: pcf-config
              mountPath: /root/free5gc/config/pcfcfg.yaml
              subPath: pcfcfg.yaml
      volumes:
        - name: pcf-config
          configMap:
            name: pcf
